management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /manegment
      exposure:
        include: "health"
spring:
  application:
    name: job4j-url-shortcut
    description: Сервис предоставляющий API для конвертации URL адресов в короткую ссылку
  datasource:
    url: ${DB_DEFAULT_URL}
    username: ${DB_DEFAULT_USERNAME}
    password: ${DB_DEFAULT_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        order_by:
          default_null_ordering: last
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    root: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: "UTC"
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        prettyPrint: false
        appendLineSeparator: true
        includes: [ timestamp, threadName, level, loggerName, message, mdc, exception ]
        flattenMdc: true
server:
  error:
    include-message: always
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

